### PR TITLE
Copula ABC

### PR DESCRIPTION
**Pull request by kskyten**
#### Summary:
Add a copula ABC method.. See the notebook [here](https://github.com/kskyten/elfi-notebooks/blob/copula_abc/gaussian_copula.ipynb). The results do not look as good as in the paper. I'm not sure why. Might be because of differences in the ABC algorithms. However, the copula method is approximating the marginals better and the dimensionality of the inference problem is irrelevant for the performance, unlike in rejection ABC for example.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):
Aalto University

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD3 (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by kskyten** [comment]
I'm open to any suggestions. Please note that the models in the paper were fairly easy to formulate, but in general the structure could be more complicated. I'd rather not restrict the API to special cases.

**Comment by kskyten** [comment]
Closed in favor of #227 and the copula ABC implementation in zoo.

**Comment by xuhuifan** [comment]
Hi Vuolleko, 

This is Xuhui and I am currently a postdoc working with Scott Sisson. I am now implementing the code of Copula ABC. However, When I check your code in he zoo repository, the function of elfi.distributions seems disappear. Do you know where I can find them so that I can run the ipyb code. 

Sorry for the trouble and thank you, 
Xuhui

**Comment by vuolleko** [comment]
Hi Xuhui,

The experimental Copula code is scattered in this PR, #227 and the Zoo area https://github.com/elfi-dev/zoo/tree/master/copula_abc. These were written by @kskyten so he knows the details of this implementation.

**Pull request closed without merging**
