### PR TITLE
Refactor ABC-SMC-methods.

### PR DESCRIPTION
**Pull request by hpesonen**
#### Summary:
Refactored samplers.py and removed duplicate code.

#### Please make sure

- [ ] You have updated the CHANGELOG.rst
- [ ] You have provided a short summary of your changes (see previous section)
- [ ] You have listed the copyright holder for the work you are submitting (see next section)

If your contribution adds, removes or somehow changes the functional behavior of the package, please check that

- [ ] You have included or updated all the relevant documentation 
- [ ] You have added appropriate unit tests to ensure the new features behave as expected

and the proposed changes pass all unit tests (check step 6 of CONTRIBUTING.rst for details)

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD3 (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Review by uremes — COMMENTED** [review]
the update looks good but i wanted to propose/discuss a modification that would take it one step further! i uploaded it as a commit since i needed to touch code in several functions, but i think the commit should be simple to remove in case this is not a direction we want to move to :)

**Review by hpesonen — COMMENTED** [review]
Sure! looks good. I'd suggest that after this, PRs would we reviewed as such and major refactorings would be made separate PRs instead of committing to earlier PRs, e.g. I can't approve the changes as the original author of the PR and the review process becomes unnecessarily convoluted. Small fixes and corrections as commits to the PRs are fine.

**Review by uremes — APPROVED** [review]
true it became a little complicated, sorry about that. i'll write comments instead next time or indeed make a separate pr.

**Comment by hpesonen** [comment]
> true it became a little complicated, sorry about that. i'll write comments instead next time or indeed make a separate pr.

No problem - it was a good addition!

**Pull request merged**
